name: Sync Blog Posts

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时执行一次（UTC）
  workflow_dispatch:       # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run sync script
        run: pnpm sync-blog

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/blog
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: sync blog posts"
          git push
